
#define CLICKER2

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <ctype.h>
#include "mcc_generated_files/system.h"
#include "mcc_generated_files/tmr3.h"
#include "main.h"
#include "cmd_wrapper.h"
#include "timer_wrapper.h"
#include "usb_wrapper.h"

#define LINELEN 255
char G_txLine[LINELEN];

int main(void)
{
    SYSTEM_Initialize(); // Generated by MCC
    TMR3_SetInterruptHandler(&TMR3_callBack);
    TMR3_Start();
    while (1)
    {
        CMD_processCommand();
        USB_sendPrintBuffer();
    }
    return 1;
}


