

#define CLICKER2

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <ctype.h>
#include "mcc_generated_files/system.h"
#include "mcc_generated_files/usb/usb.h"
#include "mcc_generated_files/interrupt_manager.h"
#include "mcc_generated_files/i2c3.h"
#include "mcc_generated_files/spi2.h"
#include "mcc_generated_files/tmr3.h"
#include "main.h"
#include "cmd_wrapper.h"
#include "flash_wrapper.h"
#include "gpio_wrapper.h"
#include "dac_wrapper.h"
#include "misc_wrapper.h"
#include "timer_wrapper.h"
#include "trigger_wrapper.h"
#include "usb_wrapper.h"

#define LINELEN 255
char G_txLine[LINELEN];

int main(void)
{
    SYSTEM_Initialize(); // Generated by MCC

    TMR3_SetInterruptHandler(&TMR3_callBack);
    TMR3_Start();
    uint16_t pollingLoopCnt = 0;
    while (1)
    {
        pollingLoopCnt = (pollingLoopCnt + 1) % 3000;
        CMD_handleUSB();
        
        // TIME_interp();
        USB_flushPrintBuffer();

#ifdef CLICKER2
        GPIO_set(LED1, TRIG_isSignalOn());
#endif
    }
    return 1;
}


